### ISSUE TITLE
Echo.socketId() undefined

### ISSUE THREAD

**Issue by rickbolton** [laravel/echo#104]
I'm trying to setup a toOthers() broadcast for a Dropzone

I've tried to add the X-Socket-ID to Dropzone but when I do Echo.socketId() it is undefined. 

My setup of Echo is 

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'key',
    cluster: 'eu',
    encrypted: true
})
console.log(Echo.socketId()) // undefined
```

Within my package.json I have laravel-echo 1.2.5

**Comment by JGdijk** [comment]
I had the same problem. What happens is that your console.log fires before the connection has been instantiated (because it happens async) and therefore socketId() will fire undefined. You will see that if you put a timeout on your console.log() you will be able to receive the socketId.

I have been looking for an event that fires when the connection has been made to hook in to it but have not found it. (i am using socket.io, i actually have seen somebody find this hook using pusher but can't find the post anymore)

**Comment by rickbolton** [comment]
Thanks, I'll test that and see whether I can make any progress with that in mind. Let me know if you find that post 👍🏻

**Comment by JGdijk** [comment]
Here it is [click](https://github.com/laravel/framework/issues/15466)

**Comment by rickbolton** [comment]
Perfect, I'll give that a try. Thanks for your help!

**Comment by Dubansoft** [comment]
In my case i discovered that Data Saving mode in mobile browsers blocks socketId from being defined...

Solved by disabling Lite Mode https://support.google.com/chrome/answer/2392284?co=GENIE.Platform%3DAndroid&hl=en-GB

**Comment by ppisecky** [comment]
I scanned through Echo source and Pusher docs and here's a solution:

```javascript
window.Echo.connector.pusher.connection.bind('connected', function () {
    window.axios.defaults.headers.common['X-Socket-Id'] = window.Echo.socketId();
});
```

Though I have to say that I'm not a massive fan.

**Comment by eightyfive** [comment]
Same as @ppisecky but for socket.io client:

```js
  async getSocketId() {
    return new Promise(resolve =>
      Echo.connector.socket.on('connect', () =>
        resolve(Echo.socketId()),
      ),
    );
  }
```

**Comment by tranvanhieu01012002** [comment]
my solution after @eightyfive 's answer not work anymore:
` const [socketId, setSocketId] = useState();
useEffect(() => {
setSocketId(Echo.connector.socketId());
});
// set socketId on your request:
 const option = {};
 option["X-Socket-ID"] = socketId;
// your fetch request with option
`
