### ISSUE TITLE
Listen Event assumes "App\Events" prefix

### ISSUE THREAD

**Issue by scs-ben** [laravel/echo#118]
If I broadcast an event as "event" and have a listener set up:
Echo.channel('channel').listen('event')...
Echo will not catch the event. However, if I broadcast as "App\Events\event", Echo will catch it.

Please tell me this is a bug.

**Comment by tlaverdure** [comment]
By default, Echo has a namespace prefixed before each event name. However, you can remove the namespace in your config.


``` js
new Echo({
    ...
    namespace: false,
    ...
});

```

[Reference](https://github.com/laravel/echo/commit/50c84b4417a74b893f8bc412795654eda49172df)

**Comment by scs-ben** [comment]
Thanks for the quick reply

**Comment by dipit2007** [comment]
You can also use  Echo.channel('channel').listen('.event') {DOT before event }

**Comment by nablidev** [comment]
I think the `namespace` option and how it can be set to `false` should be included in the official [documentation](https://laravel.com/docs/master/broadcasting#client-pusher-channels) for Laravel Echo because having to prefix the event name with a `.` is confusing a lot of developers that are new to Laravel Echo.

Some examples other than this [issue](https://github.com/laravel/echo/issues/118) are the following: [Laracasts](https://laracasts.com/discuss/channels/laravel/laravel-echo-all-the-names-of-the-events-must-be-prefixed-with-a-dot?page=1&replyId=892739) and [Stackoverflow](https://stackoverflow.com/questions/43927792/laravel-echo-is-no-listening/66099220#66099220)

```js

new Echo({
    ...
    namespace: false,
    ...
});

```
