### ISSUE TITLE
How do I add a new type of connector?

### ISSUE THREAD

**Issue by jpmec** [laravel/echo#155]
I'm looking in the echo.ts constructor at lines 44-48

        if (this.options.broadcaster == 'pusher') {
            this.connector = new PusherConnector(this.options);
        } else if (this.options.broadcaster == 'socket.io') {
            this.connector = new SocketIoConnector(this.options);
        }

If I am writing my own custom websockets server (not Pusher or Socket.io) to be compatible with Echo, how do I configure/extend Echo to use a new custom connector?

I've tried to extend class Echo, but I'm not getting very far with that.

**Comment by kohenkatz** [comment]
I am writing my own WebSocket server, and had the same question. I haven't decided for sure, but here are my two options:

1. Write a PR for Echo to add custom connectors.
2. Write my client-side JS code to have the same API as Socket.io has, then load my JS file instead of the Socket.io JS file.

I am currently leaning toward the latter solution, because it is likely easier, but I may still do the former.

**Comment by simonhamp** [comment]
@kohenkatz @jpmec I'm in the same boat right now (using a [Ratchet](http://socketo.me/) server) and would really like to collab with others on the Echo implementation.

I've booted up a fork of Echo here: https://github.com/simonhamp/echo. I have a working socket connection in the browser now and basically the same API as the SocketIO implementation, it just needs stressing for bugs.

All work is being done in my [`ratchet-connector` branch](https://github.com/simonhamp/echo/tree/ratchet-connector).

**!!! DON'T USE THIS IN PRODUCTION !!!**

To use the new Ratchet broadcaster, simply change the Echo instantiation in your `resources/assets/js/bootstrap.js` to this:

```js
window.Echo = new Echo({
    broadcaster: 'ratchet',
    host: 'ws://0.0.0.0:8080' // Change as appropriate
});
```

Hope this helps. I'm continuing my development and am hoping to get it to a point where it can be merged into the official Echo package.

**Comment by driesvints** [comment]
I think support for custom connecters if something we may consider if it was implemented in a nice and clean way.

**Comment by simonhamp** [comment]
Any pointers for what’s considered “clean” @driesvints

**Comment by driesvints** [comment]
Think basically comes down to allowing a custom connector being passed in the options list and switching the connector type to a new type "custom". Not 100% sure though.

**Comment by sun-3211** [comment]
1.
```
    if (this.options.broadcaster == 'pusher') {
        this.connector = new PusherConnector(this.options);
    } else if (this.options.broadcaster == 'socket.io') {
        this.connector = new SocketIoConnector(this.options);
    } else if (typeof this.options.broadcaster == "function") {
        this.connector = new this.options.broadcaster(this.options);
    }
    const Echo = new Echo({broadcaster:RatchetConnector,host: 'ws://0.0.0.0:8080'});
```
2.
```
const Echo = new Echo({broadcaster: 'null',host: 'ws://0.0.0.0:8080'});
Echo.connector = new RatchetConnector(Echo.options);
```

**Comment by kohenkatz** [comment]
I like the first suggestion by @sun-3211 - provide the name (e.g. `pusher`, `socket.io`) for the built-in connectors, and provide a function that returns the connector for your own custom connector.

**Comment by driesvints** [comment]
Yeah looks ok.

**Comment by dakujem** [comment]
Any idea as to _when_ the custom connectors could be possible?

**Comment by driesvints** [comment]
@dakujem as soon as someone sends in a PR.

**Comment by InstanceOfMichael** [comment]
@dakujem symphony added support for the mercure protocol. 

It seems that we could leverage http2 multiplexing (single connection) and use less battery on mobile devices (compared to pusher/websockets). mercure is written in golang so it would be faster and use less ram than the current nodejs websocket server. Symfony just released a mercure module, so we could probably borrow 99% of the work from them. "Http2/3 doesn't support websockets" is sort of the big buzz recently.

https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/

https://medium.com/@dunglas/http-2-speed-up-your-apps-and-dispatch-real-time-updates-symfony-and-api-platforms-features-76fdc5bf6339

**Comment by kohenkatz** [comment]
@InstanceOfMichael That looks really interesting, but one possible issue with mercure is that the reference implementation of the server is under the AGPL license, which many commercial users are not allowed to use. The Symfony component doesn't actually run the server, it just pushes updates to the running server.

(Note: This comment is not intended to start a debate about licensing. It is only meant to draw attention to a potential issue. The reason that commercial users are scared of AGPL is that there are some legal opinions that believe that building your application around AGPL code automatically requires your whole application to be AGPL-licensed, even if you haven't actually made modifications to the AGPL component because the AGPL component is "an integral part of your application's infrastructure".)
