### ISSUE TITLE
Echo with Vue, axios not worked.

### ISSUE THREAD

**Issue by whdckszxxx** [laravel/echo#179]
Listening to a channel from Vue component's `mounted` hook didn't work.

So I worked around for hours and found that using `setTimeout` in mounted hook made `Echo` work.

Example:
```
mounted() {
  setTimeout(() => {
    Echo.channel('test')
      .listen('TestEvent', e => { console.log(e) });
  }, 1000);
}
```

I don't know why but I just guess it's because `Echo` is not completely ready to subscribe from `laravel-echo-server` when the `mounted` hook is called. 

If I'm guessing right, is there any way to check `Echo` is completely ready to listen? 

I tried to find method or property to get Echo's current state but I couldn't. It would be great if I can get any `Promise` which is going to resolve when `Echo` is ready to listen.

Thanks for great framework.

**Comment by wdmtech** [comment]
Can't verify but maybe 

```js
this.$nextTick(() => { ... })
```

**Comment by unr** [comment]
@wdmtech's proposal will solve your problem at a low level - instead of trying an arbitrary setTimeout, you can use `$nextTick` to know when the dom is updated.

However, the actual issue has to do with how you've set up your Echo instance.

It looks like you're just calling `Echo` globally, and its not part of your Vue App.

The actual issue you're having, is **the way you have set up Laravel Echo, isn't prepared before this component mounts**

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.

**Comment by JayVynch** [comment]
i am experiencing same and if this issue has been solved please direct me to the link so i can fix my error
