### ISSUE TITLE
Build echo.iife.js broken

### ISSUE THREAD

**Issue by neoteknic** [laravel/echo#336]
- Echo Version: 1.11.7
- Laravel Version: 9.10.0
- PHP Version: 8.1.5
- NPM Version: 8.5.5
- Node Version: 17.8.0

### Description:
The echo.iife.js is broken in latest version.

### Steps To Reproduce:

Use laravel-echo/dist/echo.iife.js with 1.11.7 : error in console  : Uncaught TypeError: Echo is not a constructor
No problem on 1.11.4
Fix : revert to 1.11.4 echo.iife.js fix the problem

**Comment by taylorotwell** [comment]
No idea how to fix it. So will need more details on what I am supposed to do.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Hi there, we managed to replicate this. But because this is using echo in an unintended way that isn't documented we've decided to not consider this a bug, sorry. Please try to convert your setup in a documented way. Thanks
